FROM ubuntu:14.04

RUN (apt-get update && apt-get install -y apt-transport-https wget &&\
  wget -qO- 'https://pgp.mit.edu/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | apt-key add --import &&\
  echo "deb https://packages.docker.com/1.10/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list &&\
  apt-get clean)

ENV DOWNLOAD_DIR /data
CMD apt-get update && apt-get -d install -y docker-engine && cp /var/cache/apt/archives/*.deb ${DOWNLOAD_DIR}
